FIND_PATH(GLFW3_INCLUDE_DIR GLFW/glfw3.h)

FIND_LIBRARY(GLFW3_LIBRARY NAMES glfw)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(
    GLFW3 REQUIRED_VARS
    GLFW3_INCLUDE_DIR
    GLFW3_LIBRARY)
